<a href="https://colab.research.google.com/github/Geofgabriel/Intro-Python-para-algebra-lineal/blob/main/Notebooks/01_Primeros_pasos_con_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRIMEROS PASOS EN PYTHON

Primero: *repaso por el entorno de la notebook*

Segundo: hablemos un poco de los datos (y tipos de datos) que podemos encontrarnos.

In [ ]:
t = 'hello world!'
print(t)
t

hello world!


'hello world!'

In [ ]:
p = 2
print(p)
p

2


2

A continuación veamos las operaciones básicas en Python

In [ ]:
1+1

2

In [ ]:
5*8

40

In [ ]:
4.5/2

2.25

In [ ]:
5*2+10-(10/5)

18.0

In [ ]:
4**2

16

Ahora...Que pasa con una raíz cuadrada?

$$\sqrt{2} = 2^{(\frac{1}{2})}$$

In [ ]:
4**(1/2)

2.0

Otra opción es utilizar alguna librería...esta cuenta es muy sencilla y no trae problemas en cuanto a su lectura en el programa y no interesa su performance del cálculo. No obstante, en otras situaciones es conveniente utilizar otras opciones.

In [ ]:
sqrt(4)

NameError: ignored

In [ ]:
import math

math.sqrt(4)

2.0

Podemos ver que fácilmente se realiza cualquier tipo de operación básica. Uno de los fuertes de este lenguaje es la cantidad de librerías para hacer lo que se necesite (hay de todo!).

Particularmente existen librerías con respectivos módulos para al cálculo numérico, con un fuerte foco en el álgebra lineal. 
Éste es nuestro interés, y para empezar a meternos de a poquito utilizaremos
[Scipy](https://www.scipy.org/). En particular, los paquetes [Sympy](https://www.sympy.org/en/index.html) y [Numpy](https://numpy.org/doc/stable/index.html). 

Para poder utilizar estos paquetes se los convoca  mediante:



```
import sympy as sy
import numpy as np
import scipy as sp
```

Esto se hace solo una vez al principio del programa. Lo que estamos haciendo con el "as np", por ejemplo, es importar el módulo NumPy como una variable de nombre `np`. A esta variable la usaremos para llamar todas las funciones y objetos que tiene `NumPy`, `Scipy` o `Sympy`. Esto sirve también para *sp* y cualquier otro módulo que necesitemos. 

*Observación: Esto en realidad se puede realizar en cualquier parte del código pero antes de utilizar alguna de sus dependencias.*

In [ ]:
import numpy as np # el símbolo # se utiliza para hacer comentarios en el código. Esta parte la pasa por el alto Python.

# 2+3

## Sympy

Esta librería permite trabajar de manera simbólica. Esto es trata a los objetos matemáticos de forma simbólica. Esto significa que los objetos matemáticos se representan exactamente, no aproximadamente, y las expresiones matemáticas con variables no evaluadas se dejan en forma simbólica.

Veamos un ejemplo:

In [ ]:
import sympy as sy

sy.sqrt(4)

2

pero que pasa con $\sqrt 3$ ?

In [ ]:
math.sqrt(3)

1.7320508075688772

In [ ]:
sy.sqrt(3)

sqrt(3)

Conclusiones?









Ahora bien, para comenzar necesitamos poder definir matrices y vectores

In [ ]:
M = sy.Matrix([[1,0,0],[0,1,0],[0,0,1]])
M

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [ ]:
print('las dimensiones son:',M.shape)

las dimensiones son: (3, 3)


In [ ]:
V = sy.Matrix([1,2,3])
V

Matrix([
[1],
[2],
[3]])

In [ ]:
print('las dimensiones son:',V.shape)

las dimensiones son: (3, 1)


In [ ]:
B = sy.Matrix([1,2,3]).T
B

Matrix([[1, 2, 3]])

In [ ]:
print('las dimensiones son:',B.shape)

las dimensiones son: (1, 3)


## Numpy
NumPy es el paquete fundamental para el cómputo científico. A diferencia de Sympy, ahora podemos trabajar de forma "exacta". Numpy es una librería de Python que provee como elemento mas importante al objeto 
multidimensional *array*.
Esto nos va a permitir representar vectores y matrices. Luego con ellos podemos realizar todo tipo de operaciones (aunque hay que tener cuidado con otros tipos de datos).

### Vector y matrices

In [ ]:
u_fil = np.array([1,0,0])
u_fil

array([1, 0, 0])

otra forma, mas elegante, para poder ver lo que guardamos en *u* es utilizar print()

In [ ]:
print('El vector es u =',u_fil)

El vector es u = [1 0 0]


In [ ]:
u_col = np.array([[1],[0],[0]])
print('El vector es u =',u_col)

El vector es u = [[1]
 [0]
 [0]]


Para representar una matriz lo hacemos de la siguiente forma:

In [ ]:
w = np.array(([1,0,0],[0,1,0],[0,0,1]))
print('w =',w)

w = [[1 0 0]
 [0 1 0]
 [0 0 1]]


## Avanzando con Numpy

Ahora, podemos ver que info tienen estas variables que definimos llamando a los atributos que tienen por ser parte de Numpy.

In [ ]:
u_col.ndim #vamos la dimensión

2

In [ ]:
u_col.shape # la dimensión pero vista como una tupla

(3, 1)

In [ ]:
u_col.size # el tamaño del arreglo

3

Lo mismo vale para matrices

In [ ]:
print('dimensión de w:',w.ndim)
print('la dimensión como tupla:',w.shape)
print('el tamaño del arreglo w:',w.size)

dimensión de w: 2
la dimensión como tupla: (3, 3)
el tamaño del arreglo w: 9


Ahora bien, los arreglos se pueden crear de tres formas distintas:


1.   Como lista o tupla que vimos recién 
2.   A partir de funciones de Numpy
3.   Cargando un archivo






Entonces, el primer ítem ya lo vimos anteriormente. Podemos ver un ejemplo mas, pero ahora con números complejos. Obsevar que es recomendable, cuando se declara la variable *nro_c* especificar que tipo de dato se guardará en ella mediante *dytpe*.

In [ ]:
nro_c = np.array([1+1j,2j],dtype=complex)
print('El nro complejo es:',nro_c)

El nro complejo es: [1.+1.j 0.+2.j]


Podemos ver que tenemos un número complejo donde se representa al nro imagniario con *j* en lugar de *i* que es como suele aparcer en la bibliografía.

In [ ]:
print('Podemos quedarnos con la parte real de nro_c:',nro_c.real)
print('y podemos quedarnos con la parte imaginaria nro_c:',nro_c.imag)

Podemos quedarnos con la parte real de nro_c: [1. 0.]
y podemos quedarnos con la parte imaginaria nro_c: [1. 2.]


Claramente si tenemos que escribir arreglos con muchos valores o arreglos particulares como la matriz identidad pero de grandes dimensiones esto no es cómodo. Para esto se pueden utilizar ciertas *funciones* que tiene Numpy.

In [ ]:
v1 = np.arange(-10,10)
v1

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [ ]:
v2 = np.linspace(0,100,4)
v2

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [ ]:
v3 = np.zeros(10)
v3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
M = np.ones((5,5))
M

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
I = np.eye(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
diag_M = np.diag(I)
diag_M

array([1., 1., 1., 1., 1.])

In [ ]:
np.trace(M)

5.0

Por último, es posible crear la matriz cargando un archivo. Esto también lo podemos hacer con Numpy (dependiendo del formato). En general, se trabaja con archivos formato *.txt* o *.dat* ya que luego es posible abrirlos con cualquier otro programa. 

Una forma de hacerlo es mediante la función *loadtxt*:

```
d = np.loadtxt('nombre del archivo.txt')
```

donde, al ejecutar esta celda, se guarda la info del archivo en la variable *d*.


In [ ]:
d = np.loadtxt('/content/drive/MyDrive/Algebra_y_python/Matriz_A.txt') 
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Esto es todo por ahora...

En esta notebook hemos aprendido sobre:

* operaciones básicas con Python
* librerías de interés para el algebra lineal y podes hacer gráficos simples
* Una introducción de matrices y vectores con *Numpy*

