<a href="https://colab.research.google.com/github/Geofgabriel/Intro-Python-para-algebra-lineal/blob/main/Primeros_pasos_con_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PRIMEROS PASOS EN PYTHON

Para empezar veamos las operaciones básicas en Python

In [1]:
1+1

2

In [2]:
5*8

40

In [3]:
4/2

2.0

In [4]:
5*2+10-(10/5)

18.0

In [8]:
4**2

16

Ahora...Que pasa con una raíz cuadrada?

$$\sqrt(2) = 2^{(\frac{1}{2})}$$

In [10]:
4**(1/2)

2.0

Otra opción es utilizar alguna librería...esta cuenta es muy sencilla y no trae problemas en cuanto a su lectura en el programa y no interesa su performance del cálculo. No obstante, en otras situaciones es conveniente utilizar otras opciones.

In [5]:
sqrt(4)

NameError: ignored

In [12]:
import math

math.sqrt(4)

2.0

Podemos ver que fácilmente se realiza cualquier tipo de operación básica. Uno de los fuertes de este lenguaje es la cantidad de librerías para hacer lo que se necesite (hay de todo!).

Particularmente existen librerías con respectivos módulos para al cálculo numérico, con un fuerte foco en el álgebra lineal. 
Éste es nuestro interés, y para empezar a meternos de poquito utilizaremos
[Scipy](https://www.scipy.org/) y [Numpy](https://numpy.org/doc/stable/index.html) (que en realidad es un paquete del ecosistema de Scipy).

Para poder utilizar estos paquetes se los convoca  mediante:



```
import numpy as np
import scipy as sp
```

Esto se hace solo una vez al principio del programa. Lo que estamos haciendo con el "as np" es importar el módulo NumPy como una variable de nombre np. A esta variable la usaremos para llamar todas las funciones y objetos que tiene NumPy. Esto sirve también para sp y cualquier otro módulo que necesitemos. 

*Observación: Esto en realidad se puede realizar en cualquier parte del código pero antes de utilizar alguna de sus dependencias.*

In [18]:
import numpy as np # el símbolo # se utiliza para hacer comentarios en el código. Esta parte la pasa por el alto Python.

# 2+3

## Numpy
NumPy es el paquete fundamental para el cómputo científico. Es una librería de Python que provee como elemento mas importante al objeto 
multidimensional array
Esto nos va a permitir representar vectores y matrices. Luego con ellos podemos realizar todo tipo de operaciones (aunque hay que tener cuidado con otros tipos de datos).

### Vector y matrices

In [19]:
u = np.array([1,0,0])
u

array([1, 0, 0])

otra forma, mas elegante, para poder ver lo que guardamos en *u* es utilizar print()

In [17]:
print('El vector es u =',u)

El vector es u = [1 0 0]


Para representar una matriz lo hacemos de la siguiente forma:

In [21]:
w = np.array(([1,0,0],[0,1,0],[0,0,1]))
print('w =',w)

w = [[1 0 0]
 [0 1 0]
 [0 0 1]]


Ahora, podemos ver que info tienen estas variables que definimos llamando a los atributos que tienen por ser parte de Numpy.

In [22]:
u.ndim #vamos la dimensión

1

In [23]:
u.shape # la dimensión pero vista como una tupla

(3,)

In [24]:
u.size # el tamaño del arreglo

3

Lo mismo vale para matrices

In [26]:
print('dimensión de w:',w.ndim)
print('la dimensión como tupla:',w.shape)
print('el tamaño del arreglo w:',w.size)

dimensión de w: 2
la dimensión como tupla: (3, 3)
el tamaño del arreglo w: 9


Ahora bien, los arreglos se pueden crear de tres formas distintas:


1.   Como lista o tupla que vimos recién 
2.   A partir de funciones de Numpy
3.   Cargando un archivo


Entonces, el primer ítem ya lo vimos anteriormente. Podemos ver un ejemplo mas ahora con números complejos. Obsevar que es recomendable, cuando se declara la variable *nro_c* especificar que tipo de dato se guardará en ella mediante *dytpe*.


In [31]:
nro_c = np.array([1+1j,2j],dtype=complex)
print('El nro complejo es:',nro_c)

El nro complejo es: [1.+1.j 0.+2.j]


Podemos ver que tenemos un número complejo donde se representa al nro imagniario con *j* en lugar de *i* que es como suele aparcer en la bibliografía.

In [33]:
print('Podemos quedarnos con la parte real de nro_c:',nro_c.real)
print('y podemos quedarnos con la parte imaginaria nro_c:',nro_c.imag)

Podemos quedarnos con la parte real de nro_c: [1. 0.]
y podemos quedarnos con la parte imaginaria nro_c: [1. 2.]


Claramente si tenemos que escribir arreglos con muchos valores o arreglos particulares como la matriz identidad pero de grandes dimensiones esto no es cómodo. Para esto se pueden utilizar ciertas *funciones* que tiene Numpy.

In [34]:
v1 = np.arange(0,10,3)
v1

array([0, 3, 6, 9])

In [36]:
v2 = np.linspace(0,100,4)
v2

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [37]:
v3 = np.zeros(10)
v3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
M = np.ones((5,5))
M

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
I = np.eye((5))
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
diag_M = np.diag(I)
diag_M

array([1., 1., 1., 1., 1.])

In [44]:
np.trace(M)

5.0